version: '3.1'

services:
  db:
    image: postgres
    container_name: pms_db
    ports:
      - "54324:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql